# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c4503b6a10bc7e0db1593aa5376f830cacd8d78cf52314374d93c7398f9e4d89187393ac6e2f04ec422d5e0fbf6d1702ad30150c697a9422b732e07bd0cc32e

test:
  secret_key_base: 64aa5d7eac62492422e717e1d03ce1c178093e1a98f8a11166c13a9248f38f1046f211853dd1046f1dc8774778b0298e5e1aae5d8f0c1c0212223da959bb5892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
